name: save-it

# for creating a virtual environment includes all the project's dependencies:
# install conda.
# use: conda env update -f environment.yml
# activate the environment (everytime): conda activate save-it

channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
      - firebase_admin
      - requests
      - Flask
      - Flask-RESTful
      - Flask-Swagger-UI
      - flasgger
      - injector
      - marshmallow-dataclass
      - pytest
