name: save-it

# for creating a virtual environment includes all the project's dependencies:
# install conda.
# use: conda env update -f environment.yml
# activate the environment (everytime): conda activate watch-it

channels:
  - defaults
  - conda-forge
dependencies:
  - flask
  - pip
  - pip:
      - firebase_admin
      - requests
