name: save-it

# for creating a virtual environment includes all the project's dependencies:
# install conda.
# use: conda env update -f environment.yml
# activate the environment (everytime): conda activate save-it

channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.12.3
  - pip
  - pip:
      - firebase_admin
      - requests
      - Flask
      - injector
      - email-validator
      - phonenumbers
      - marshmallow-dataclass
      - pytest
      - pytest-mock
      - flask-restx
      - flask-cors
